(ql:quickload "str")

(defparameter *input-file* #P"input.txt")
(defparameter *input* (uiop:read-file-string *input-file*))

(defun opcode (instruction-code)
  (mod instruction-code 100))

(defun parameter-mode (instruction-code parameter-index)
  (nth (- parameter-index 1)
       (reverse (map 'list #'digit-char-p
		     (prin1-to-string (floor (/ instruction-code 100)))))))

(defun get-parameter (program instruction-pointer parameter-index)
  (let ((mode (parameter-mode (aref program instruction-pointer) parameter-index)))
    (if (eql 1 mode)
	(aref program (+ parameter-index instruction-pointer))
	(aref program (aref program (+ parameter-index instruction-pointer))))))


(defun execute (program inputs)
  (defun execute-instruction (i inputs outputs)
    ;(format t "~a ~a ~a ~a~%" program i inputs outputs)
    (let ((opcode (opcode (aref program i))))
      (cond
	((= opcode 99)
	 (return-from execute-instruction (values program outputs)))
	((= opcode 1)
	 (setf (aref program (aref program (+ 3 i)))
	       (+ (get-parameter program i 1)
		  (get-parameter program i 2)))
	 (execute-instruction (+ i 4) inputs outputs))
	((= opcode 2)
	 (setf (aref program (aref program (+ 3 i)))
	       (* (get-parameter program i 1)
		  (get-parameter program i 2)))
	 (execute-instruction (+ i 4) inputs outputs))
	((= opcode 3)
	 (setf (aref program (aref program (+ 1 i)))
	       (car inputs))
	 (execute-instruction (+ i 2) (cdr inputs) outputs))
	((= opcode 4)
	 (execute-instruction (+ i 2) inputs (cons (get-parameter program i 1) outputs)))
	((= opcode 5)
	 (if (/= 0 (get-parameter program i 1))
	     (execute-instruction (get-parameter program i 2) inputs outputs)
	     (execute-instruction (+ i 3) inputs outputs)))
	((= opcode 6)
	 (if (= 0 (get-parameter program i 1))
	     (execute-instruction (get-parameter program i 2) inputs outputs)
	     (execute-instruction (+ i 3) inputs outputs)))
	((= opcode 7)
	 (if (< (get-parameter program i 1) (get-parameter program i 2))
	     (setf (aref program (aref program (+ i 3))) 1)
	     (setf (aref program (aref program (+ i 3))) 0))
	 (execute-instruction (+ i 4) inputs outputs))
	((= opcode 8)
	 (if (= (get-parameter program i 1) (get-parameter program i 2))
	     (setf (aref program (aref program (+ i 3))) 1)
	     (setf (aref program (aref program (+ i 3))) 0))
	 (execute-instruction (+ i 4) inputs outputs)))))
  (execute-instruction 0 inputs nil))

(defun parse-program (program-string)
  (map 'vector #'parse-integer (str:split "," program-string)))

(defun part1 ()
  (car (nth-value 1 (execute (parse-program *input*) '(1)))))

(defun part2 ()
  (car (nth-value 1 (execute (parse-program *input*) '(5)))))
